# Generated by Django 5.1.15 on 2026-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_seed_default_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='kind',
            field=models.CharField(choices=[('INSCRIPTION', "Droit d'inscription"), ('COTISATION', 'Cotisation mensuelle'), ('BRANCHE_FEMME', 'Accès espace Femme'), ('BRANCHE_ENFANT', 'Accès espace Enfant'), ('DON', 'Don volontaire'), ('REMBOURSEMENT', 'Remboursement')], db_index=True, max_length=20, unique=True),
        ),
    ]
