# Generated by Django 5.1.15 on 2026-07-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom logique du template (ex. 'otp_verification')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "content_sid",
                    models.CharField(
                        help_text="Content SID Meta/Twilio (ex. HXb5b32575a...)",
                        max_length=100,
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        default="fr",
                        help_text="Code langue Meta (fr, en, …)",
                        max_length=10,
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Liste des noms de variables, p.ex. ["code", "prenom"]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template WhatsApp",
                "verbose_name_plural": "Templates WhatsApp",
                "db_table": "whatsapp_templates",
            },
        ),
    ]
