# Generated by Django 5.1.15 on 2026-07-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_whatsapptemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, default="", verbose_name="Facebook"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, default="", verbose_name="LinkedIn"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, default="", verbose_name="Twitter / X"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, default="", verbose_name="Instagram"),
                ),
                (
                    "youtube",
                    models.URLField(blank=True, default="", verbose_name="YouTube"),
                ),
                (
                    "tiktok",
                    models.URLField(blank=True, default="", verbose_name="TikTok"),
                ),
                (
                    "whatsapp",
                    models.URLField(blank=True, default="", verbose_name="WhatsApp"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Liens sociaux",
                "verbose_name_plural": "Liens sociaux",
                "db_table": "social_links",
            },
        ),
    ]
