# Generated by Django 5.1.15 on 2026-07-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="library_pdf",
            field=models.ForeignKey(
                blank=True,
                help_text="Document PDF de bibliothèque associé au QCM",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quiz_link",
                to="content.resource",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
