# Generated by Django 5.1.15 on 2026-08-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_globalsettings"),
        ("accounts", "0003_user_referral_code"),
    ]

    operations = []
