# Generated by Django 5.1.15 on 2026-08-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_0003_globalsettings_0003_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, help_text='Code de parrainage unique (généré automatiquement).', max_length=12, null=True, unique=True),
        ),
    ]
