# Generated by Django 5.1.15 on 2026-07-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_formation_is_public'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quiz',
            name='quiz_course_xor_formation',
        ),
        migrations.AddField(
            model_name='quiz',
            name='library_pdf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='content.librarypdf'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('formation__isnull', True), ('library_pdf__isnull', True)), models.Q(('course__isnull', True), ('formation__isnull', False), ('library_pdf__isnull', True)), models.Q(('course__isnull', True), ('formation__isnull', True), ('library_pdf__isnull', False)), _connector='OR'), name='quiz_course_xor_formation_xor_pdf'),
        ),
    ]
