# Generated by Django 5.1.15 on 2026-08-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_remove_quiz_quiz_course_xor_formation_and_more"),
        ("content", "0012_quizresult_last_answers"),
    ]

    operations = []
