# Generated by Django 5.1.15 on 2026-09-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_librarypdf_cover_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['id']},
        ),
    ]
