# Generated by Django 5.1.15 on 2026-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitychannel',
            name='branche',
            field=models.CharField(choices=[('MEMBRE', 'Membres'), ('FEMME', 'Femmes'), ('ENFANT', 'Enfants')], default='MEMBRE', max_length=10),
        ),
    ]
