# Generated by Django 5.1.15 on 2026-07-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom du template chez Twilio",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identifiant logique pour le code",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Corps du message avec placeholders {{1}}, {{2}}…"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="UTILITY",
                        help_text="Catégorie Twilio : MARKETING, UTILITY, AUTHENTICATION",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="fr", help_text="Code langue (fr, en…)", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "variables_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de variables/placeholders dans le template",
                    ),
                ),
                (
                    "twilio_template_sid",
                    models.CharField(
                        blank=True,
                        help_text="Identifiant Twilio du Content Template (optionnel)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template WhatsApp",
                "verbose_name_plural": "Templates WhatsApp",
                "db_table": "whatsapp_templates",
                "ordering": ["-created_at"],
            },
        ),
    ]
