# Generated by Django 5.1.15 on 2026-08-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_seed_whatsapp_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="meta_template_name",
            field=models.CharField(
                blank=True,
                help_text="Nom exact du template approuvé dans Meta WhatsApp Manager (par défaut, le slug est utilisé)",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="category",
            field=models.CharField(
                blank=True,
                default="UTILITY",
                help_text="Catégorie du template : MARKETING, UTILITY, AUTHENTICATION",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="whatsapptemplate",
            name="name",
            field=models.CharField(
                help_text="Nom du template (Twilio / Meta Cloud API)",
                max_length=128,
                unique=True,
            ),
        ),
    ]
