# Generated by Django 5.1.15 on 2026-08-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referral',
            new_name='referrals_referre_cefb5c_idx',
            old_name='referrals_referr_idx',
        ),
        migrations.AlterField(
            model_name='affiliateconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
